from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List

from src.simulator.assistant_api import AssistantApiClient
from src.simulator.data_loader import read_jsonl, write_jsonl
from src.simulator.evaluator import evaluate_dialogue
from src.simulator.llm_client import build_llm_client
from src.simulator.roadmap_adapter import persona_from_name, seed_from_knowledge_roadmap
from src.simulator.runtime import EnterpriseUserSimulator
from src.simulator.schemas import AgentStep, UserGoalSeed, to_dict


def run_one_with_assistant_api(
    seed: UserGoalSeed,
    assistant: AssistantApiClient,
    max_turns: int,
    llm: Any,
) -> Dict[str, Any]:
    user = EnterpriseUserSimulator(seed, llm=llm)
    turns: List[Dict[str, Any]] = []
    compatible_logs: List[Dict[str, Any]] = []
    dialogue_history: List[Dict[str, str]] = []

    initial_user_step = user.step(None)
    turns.append(_user_turn(initial_user_step))
    if initial_user_step.utterance.strip():
        dialogue_history.append({"role": "user", "content": initial_user_step.utterance})

    for log_turn in range(1, max_turns + 1):
        if user.state.should_end:
            break
        assistant_text = assistant.reply(dialogue_history)
        agent_step = AgentStep(response=assistant_text, action="api_response")
        turns.append(_agent_turn(agent_step, initial_user_step.turn_id + log_turn - 1))
        dialogue_history.append({"role": "assistant", "content": assistant_text})
        history_before_reply = list(dialogue_history)

        user_step = user.step(assistant_text)
        turns.append(_user_turn(user_step))
        if user_step.utterance.strip():
            dialogue_history.append({"role": "user", "content": user_step.utterance})

        compatible_logs.append(
            build_compatible_simulation_log(
                case_id=seed.target_case_id or "",
                log_turn=log_turn,
                assistant_text=assistant_text,
                history_before_reply=history_before_reply,
                user_step=user_step,
            )
        )
        if user_step.should_end:
            break

    metrics = evaluate_dialogue(
        target_case_id=seed.target_case_id,
        turns=turns,
        final_user_state=user.state,
        max_turns=max_turns,
    )
    return {
        "dialogue_id": seed.dialogue_id,
        "target_case_id": seed.target_case_id,
        "target_title": seed.target_title,
        "simulator_version": "v1_enterprise_user_simulator",
        "turns": turns,
        "metrics": metrics,
        "compatible_logs": compatible_logs,
    }


def build_compatible_simulation_log(
    case_id: str,
    log_turn: int,
    assistant_text: str,
    history_before_reply: List[Dict[str, str]],
    user_step: Any,
) -> Dict[str, Any]:
    solution_status = "solution_accepted" if user_step.end_reason == "task_complete" else "not_solved"
    if user_step.end_reason == "patience_exhausted":
        solution_status = "assistant_unable_to_provide_effective_solution"
    return {
        "case_id": case_id,
        "module": "Simulator.step",
        "input": {
            "assistant_text": assistant_text,
            "history_before_reply": history_before_reply,
        },
        "output": {
            "turn": log_turn,
            "assistant_text": assistant_text,
            "assistant_act": {
                "assistant_act": "v1_unclassified",
                "request_summary": "original v1 simulator does not expose assistant-act classification",
                "confidence": 0.0,
                "reason": "v1 compatibility log",
            },
            "knowledge_assessment": {
                "assistant_act": "v1_unclassified",
                "matched_scope": "v1_state_machine",
                "matched_point_ids": [],
                "allowed_facts": [],
                "unknown_requested_facts": [],
                "solution_match": "target" if user_step.end_reason == "task_complete" else "none",
                "progress_status": "v1_state_machine",
                "no_more_user_info": not bool(user_step.state.pending_clarification or user_step.state.pending_deep),
                "state_update": {},
                "reason": "generated by original v1 EnterpriseUserSimulator",
            },
            "user_action": {
                "user_action": _compatible_user_action(user_step.end_reason),
                "reply": user_step.utterance,
                "state_update": {
                    "solution_status": solution_status,
                    "should_stop": user_step.should_end,
                    "stop_reason": user_step.end_reason,
                },
                "reason": "original v1 state machine",
            },
            "user_reply": user_step.utterance,
            "state": {
                "turn_count": log_turn,
                "exposed_point_ids": [],
                "rejected_external_point_ids": [],
                "action_request_count": 0,
                "how_to_check_count": 0,
                "max_how_to_check": 1,
                "pending_action_result": False,
                "last_action_summary": None,
                "pending_action_solution_match": None,
                "pending_action_result_facts": [],
                "solution_status": solution_status,
                "should_stop": user_step.should_end,
                "stop_reason": user_step.end_reason,
            },
            "simulator_variant": "v1_enterprise_user_simulator",
        },
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }


def _compatible_user_action(end_reason: str | None) -> str:
    if end_reason == "task_complete":
        return "accept_actionable_solution_and_stop"
    if end_reason == "patience_exhausted":
        return "patience_exhausted"
    return "v1_reply"


def _user_turn(user_step: Any) -> Dict[str, Any]:
    return {
        "role": "user",
        "turn_id": user_step.turn_id,
        "text": user_step.utterance,
        "should_end": user_step.should_end,
        "end_reason": user_step.end_reason,
        "state": to_dict(user_step.state),
    }


def _agent_turn(agent_step: AgentStep, turn_id: int) -> Dict[str, Any]:
    return {
        "role": "agent",
        "turn_id": turn_id,
        "text": agent_step.response,
        "recommended_case_id": agent_step.recommended_case_id,
        "action": agent_step.action,
        "evidence": agent_step.evidence,
        "metadata": agent_step.metadata,
    }


def load_selected_roadmaps(path: Path, case_ids: Iterable[str] | None = None) -> List[Dict[str, Any]]:
    selected = set(case_ids or [])
    records = []
    for record in read_jsonl(path):
        roadmap = record.get("roadmap") or {}
        case_id = str(record.get("case_id") or roadmap.get("target_case_id") or "").strip()
        if selected and case_id not in selected:
            continue
        records.append(record)
    return records


def collect_case_ids(args: argparse.Namespace) -> List[str]:
    case_ids = [case_id.strip() for case_id in (args.case_ids or []) if case_id.strip()]
    if args.case_ids_file:
        for line in Path(args.case_ids_file).read_text(encoding="utf-8").splitlines():
            text = line.strip()
            if text and not text.startswith("#"):
                case_ids.append(text.split()[0])
    return case_ids


def write_compatible_logs(records: List[Dict[str, Any]], path: Path) -> None:
    logs: List[Dict[str, Any]] = []
    for record in records:
        logs.extend(record.get("compatible_logs") or [])
    write_jsonl(logs, path)


def strip_compatible_logs(records: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    stripped = []
    for record in records:
        clean = dict(record)
        clean.pop("compatible_logs", None)
        stripped.append(clean)
    return stripped


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run original v1 EnterpriseUserSimulator on current knowledge_roadmaps.jsonl against real assistant API."
    )
    parser.add_argument("--roadmaps", required=True, help="Current knowledge_roadmaps.jsonl path")
    parser.add_argument("--output", required=True, help="V1 simulation result JSONL path")
    parser.add_argument("--simulation-log-output", help="Evaluator-compatible simulation_logs.jsonl path")
    parser.add_argument("--case_ids", nargs="*")
    parser.add_argument("--case_ids_file", help="Plain text file with one case_id per line.")
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--offset", type=int, default=0)
    parser.add_argument("--max-turns", type=int, default=8)
    parser.add_argument("--persona", default="low_tech", choices=["low_tech", "cooperative", "impatient", "vague"])
    parser.add_argument("--assistant-base-url", default="http://10.67.43.6:8338")
    parser.add_argument("--assistant-policy-base-url")
    parser.add_argument("--assistant-response-base-url")
    parser.add_argument("--assistant-timeout", type=float, default=120)
    parser.add_argument("--llm-provider", default="mock", choices=["mock", "openai-compatible"])
    parser.add_argument("--llm-base-url", default=None)
    parser.add_argument("--llm-api-key", default=None)
    parser.add_argument("--llm-api-key-env", default="LLM_API_KEY")
    parser.add_argument("--llm-model", default=None)
    parser.add_argument("--llm-timeout", type=int, default=60)
    parser.add_argument("--llm-temperature", type=float, default=0.4)
    args = parser.parse_args()

    case_ids = collect_case_ids(args)
    roadmap_records = load_selected_roadmaps(Path(args.roadmaps), case_ids or None)
    if args.offset:
        roadmap_records = roadmap_records[args.offset :]
    if args.limit:
        roadmap_records = roadmap_records[: args.limit]

    llm = build_llm_client(
        provider=args.llm_provider,
        base_url=args.llm_base_url,
        api_key=args.llm_api_key,
        api_key_env=args.llm_api_key_env,
        model=args.llm_model,
        timeout=args.llm_timeout,
        temperature=args.llm_temperature,
    )
    assistant = AssistantApiClient(
        base_url=args.assistant_base_url,
        policy_base_url=args.assistant_policy_base_url,
        response_base_url=args.assistant_response_base_url,
        timeout=args.assistant_timeout,
    )
    persona = persona_from_name(args.persona)
    seeds = [seed_from_knowledge_roadmap(record, persona=persona) for record in roadmap_records]
    results = [run_one_with_assistant_api(seed, assistant, args.max_turns, llm=llm) for seed in seeds]

    write_jsonl(strip_compatible_logs(results), Path(args.output))
    if args.simulation_log_output:
        write_compatible_logs(results, Path(args.simulation_log_output))

    print(f"Ran {len(results)} v1 roadmap/API simulations -> {args.output}")
    if args.simulation_log_output:
        print(f"Wrote evaluator-compatible logs -> {args.simulation_log_output}")


if __name__ == "__main__":
    main()
